### ISSUE TITLE
pop without scroll view

### ISSUE THREAD

**Issue by aytunch** [luunc/overscroll_pop#1]
Hi @luunc thanks for this great library and the nice gif representations.
I want to ask why you are limiting the package to only be used in scroll views?
For instance I want to use this package for stories just like in instagram. Sometimes they are only one story videos and the user needs to be able to dismiss/pop them towards the direction of their finger (not towards one of the 4 up, down, left, right)
Do you think it is a good idea?

**Comment by luunc** [comment]
Do you mean something like this?

![Demo](https://media.giphy.com/media/jBPORftNtq77Q2Lalg/giphy.gif)

At beginning, the main purpose is for ScrollView only, if you need this feature I will create a new Widget for this purpose: a full screen scaffold that can drag anywhere to pop?

**Comment by aytunch** [comment]
@luunc yes something like that but not just for an image but a full page. When the front page is being dragged, it starts moving towards users finger + sizing down and fading out all at the same time. I added 2 screen recordings to give you an inspiration. If you open a new repo for this, please inform here so I can watch and star the repo :)

https://user-images.githubusercontent.com/6442915/120184875-2889f480-c21a-11eb-91e3-74929cbd0b21.mov

Also you can find a question here. As you can see from the answers, there is no exact package which solves this need:
https://www.reddit.com/r/FlutterDev/comments/ndz41l/which_flutter_package_enables_the_page_dismiss/

**Comment by luunc** [comment]
I already created a Widget called DragToPop.
Please take a look at the document for detail.

![Demo](https://media.giphy.com/media/suIR06ewXDsrwWFszb/giphy.gif)

**Comment by aytunch** [comment]
I will be testing this tomorrow. The gif looks amazing 👍

**Comment by aytunch** [comment]
hi @luunc 
Sorry for the late reply, I tried the `DragToPop` widget and the responsiveness is very good. However I have 2 small problems.

1- I can not  see the previous Page behind the current page while dismissing. There is just a black screen. I am not sure if this is caused by this package. Do you have any idea what might be the cause?
2- Normally I have a video player in my pushed screen as the top child of a `Stack` and there is Gesture Recogniser which allows the video to be paused when a finger is being touched. This prevents `DragToPop` widget to receive gestures so for the time being I removed the video. That is why you see a white screen. How can I make this widget and the video player receive touches?

Here is a video to illustrate the first issue:

https://user-images.githubusercontent.com/6442915/120928994-db14f800-c6ef-11eb-9430-20fa7ef320e1.mp4

**Comment by luunc** [comment]
1. To see under-layer route, you need to push a route which is not opaque, something like this:
```
Navigator.of(context).push(
            PageRouteBuilder(
              transitionDuration: const Duration(milliseconds: 250),
              reverseTransitionDuration: const Duration(milliseconds: 250),
              fullscreenDialog: true,
              opaque: false,
              transitionsBuilder:
                  (_, Animation<double> animation, __, Widget child) =>
                      FadeTransition(opacity: animation, child: child),
              pageBuilder: (_, __, ___) => FullScreenDetail(url: images[index]),
            ),
          )
```
[(see example here)](https://github.com/luunc/overscroll_pop/blob/main/example/lib/full_screen_drag_to_pop_example.dart)

2. Which gesture do you use to pause the video? If that gesture overlaps `DragToPop` widget. I think you should create your own one following the code in this package, it will be more efficient.

**Comment by aytunch** [comment]
> Which gesture do you use to pause the video? If that gesture overlaps DragToPop widget. I think you should create your own one following the code in this package, it will be more efficient.

Can you show a code snippet please? I am using `onScaleStart`, `onScaleUpdate` and `onDoubleTap`

**Comment by luunc** [comment]
The full code of `DragToPop` widget: https://github.com/luunc/overscroll_pop/blob/main/lib/drag_to_pop.dart
