### ISSUE TITLE
Fade Container behind DrapToPop widget moves while page is being popped

### ISSUE THREAD

**Issue by aytunch** [luunc/overscroll_pop#4]
The semi transparent Container moves down once the DragToPop widget is popped. This makes unwanted edge seen through out the animation.

https://user-images.githubusercontent.com/6442915/120933967-24237700-c705-11eb-9386-883198fce18c.mov

![IMG_4703](https://user-images.githubusercontent.com/6442915/120933959-1bcb3c00-c705-11eb-8fab-a2ae17ace1e7.PNG)

**Comment by luunc** [comment]
That's the default route transition animation on Android.
You should create a simple route transition animation and use `Hero` widget for smooth animation instead.
Check out the example here for example: https://github.com/luunc/overscroll_pop/blob/main/example/lib/full_screen_drag_to_pop_example.dart
